spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test-app
    username: postgres
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080