spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test-app
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

auth:
  service:
    url: http://localhost:8081