server:
  port: 8888

spring:
  cloud:
    config:
      uri: http://localhost:8888
      server:
        git:
          uri: file:///${user.dir}/src/main/resources/config-repo/
          search-paths: .
          default-label: main